### ISSUE TITLE
Only one @package tag is allowed...  but only one package tag is present

### ISSUE THREAD

**Issue by rscarson** [phpDocumentor/phpDocumentor2#1339]
Getting this for every single file since yesterday's update...

**Comment by freshfelicio** [comment]
Got the same bug.

**Comment by arunu** [comment]
Me too. Any fix available ?

**Comment by olivierpons** [comment]
Still present on my debian/ phpdocumentor 2.8.2
Annoying to see same 64 errors on 64 files...
Any fix available yet?

**Comment by markbijl** [comment]
Hi everyone, I am also still experiencing this issue, any outlook on when it might be fixed..?

**Comment by rscarson** [comment]
Is this project abandoned or something? It's been a year, this is getting absurd

**Comment by mvriel** [comment]
@rscarson no, the project is far from abandoned. We are currently focussing most efforts on creating the next version of phpDocumentor. This message does not break the generation of the documentation but is a nuisance that I have yet to discover the source of.

**Comment by rscarson** [comment]
Fair enough! Sorry if I sounded rude :)

**Comment by markbijl** [comment]
Good to hear it is still being worked on! We monitor our 'documentation issues' via Jenkins and generating a checkstyle report, so I was a bit shocked when we went from a few issues to a couple of thousand...

@rscarson Would be great if we can get rid of this issue :smile:

**Comment by lsces** [comment]
Now that I've got control of things, this is the first error I need to clear. Every code base I'm working with is giving this error and obviously there is little point trying to tidy up until it has been fixed? I'm seeing other problems which are hopefully not a result of this, but @subpackage does not seem to be working as expected either.

**Comment by tarcinil** [comment]
I just wanted add that I am noticing this as well, but only when I include @package on the page-level, if this is applied at the class-level, I don't notice an error.

Another strange behavior, If you place @package at the page level, it will get mapped to the correct package in generated documents, but if you have @package at the class-level, it will get mapped to the /Default package.

I am using 2.8.4.

**Comment by NicolasCARPi** [comment]
:+1: for this issue :)

**Comment by lsces** [comment]
Can anybody indicate a previous version that pre-dates the problem. I need to get some new documentation finished, but with several thousand files I don't want to have to start restyling everything.

**Comment by rscarson** [comment]
Not to my knowledge. This is a program breaking bug the devs seem intent on ignoring.

I've switched to alternatives, and I'd recommend you do the same.

**Comment by olivierpons** [comment]
May I ask you to give the alternatives ?

**Comment by Etdashou** [comment]
http://phpdox.de/
http://www.apigen.org/
http://www.stack.nl/~dimitri/doxygen/
https://github.com/FriendsOfPHP/Sami

**Comment by mvriel** [comment]
@rscarson I take offense on your statement that we, as "the devs" seem "intent on ignoring" the issue. We have only so much resources to play with and are hard at work on shipping phpDocumentor 3 as soon as possible; since I am not paid to do this "job" and do this out of sheer love in my personal time and I do have other interests besides working every free minute of my life on phpDocumentor I hope that you understand.

I can see that there is quite a bit of frustration and I acknowledge that. But I would also like to ask for a bit of understanding that this is a complex open source project that requires a fair amount of work and we cannot do this without having open ends. Believe me if I say I rather wouldn't see them here as well.

If this frustrates so much then accept my plea for help and please help out by digging in a bit and submitting a PR. Not as a way to 'shut you up' (have seen that in other projects, I prefer to avoid such a mentality) but as a genuine request for assistance.

**Comment by mvriel** [comment]
@lsces to answer your question, I am not sure in which version this was introduced exactly; you can try out 2.7 or 2.6; I believe one of those didn't had this notice.

**Comment by rscarson** [comment]
@mvriel My comment was unnecessary, rude, and unprofessional. As my way of apologizing, I have found both the cause of, and solution to the issue...

in **phpDocumentor/Descriptor/Builder/Reflector/FileAssembler.php**, lines 44-52 package is added to the descriptor even though assembleDocBlock, called 7 lines later adds ass tags, including package.

Those lines can be removed to fix the issue.

Here is the full offending block:

    
        $packages = new Collection();
        $package = $this->extractPackageFromDocBlock($data->getDocBlock());
        if (! $package) {
            $package = $data->getDefaultPackageName();
        }
        $tag = new TagDescriptor('package');
        $tag->setDescription($package);
        $packages->add($tag);
        $fileDescriptor->getTags()->set('package', $packages);

**Comment by rscarson** [comment]
I really really really hope I did that pull request correctly

**Comment by mvriel** [comment]
@rscarson You are spot on with your analysis and this seems indeed to be the issue; the intended solution had an unfortunate side-effect that is hard to spot to I had to change the solution somewhat. 

I have moved the code that you have shown above after the assembleDocBlock method call; that will completely override the package tag instead that assembleDocBlock adds a new package tag onto it. (by just removing those lines you will lose the ability to specify a DefaultPackageName).

Unfortunately your PR was issued against branch 2.0.2 (which is an old version) so I was unable to merge that, but instead I am about to commit a fix based on your analysis as a hotfix to the master branch (with dedication to you) and at least tag a new version so that composer installation can make use of it.

When I am back home this evening I can create a PEAR and PHAR package and do a complete release but this way the composer users can at least benefit directly. (a full release takes somewhere around an hour to complete)

Thank you so much for helping us out in finding the cause for this issue and so that we may solve it.

**Comment by mvriel** [comment]
I have just tagged phpDocumentor 2.8.5 with the hotfix; it should be on packagist within a few minutes and a complete release will be done this evening

**Comment by rscarson** [comment]
Beautiful :D
Glad I could help!

**Comment by lsces** [comment]
mvriel - Mike - Many of us are only to happy to help with what have become key elements of our infrastructure, but with the level of changes - many of which I feel are totally unnecessary - trying to keep what have been totally stable projects for many years working is increasingly difficult. This is why it is important to try and avoid changes which cause general breaks in currently working systems. My own code base was virtually clean on V1 and this fix will help reduce the problems in V2 but I'm still still going to have to spend several weeks fixing what are often aesthetic changes so much so that a switch to doxygen style instead MAY be easier. I still would like to get the same hierarchic display that the V1 layout produced but I doubt I'll have any spare time to work on that any time soon :(

**Comment by mvriel** [comment]
@lsces we are always open to suggestions on how to facilitate the particular aesthetic preferences. We are trying to reinvent or re-approach how people work with documentation but I recognise that some prefer to keep a consistent look and feel.

Can you tell me what irks you most or what it is that you are missing? Perhaps it is easiest to do this by e-mail at me[AT]mikevanriel.com. I cannot promise you that I can solve everything and in what timeframe. But at the least I can listen to you and take it into account

**Comment by NicolasCARPi** [comment]
I love waking up to a fixed issue. Good job guys :)

**Comment by mvriel** [comment]
FYI: I have just uploaded a new PHAR file and packaged and published a new PEAR package with this fix in it. Thank you all for your patience and thanks to @rscarson for finding the cause

**Comment by marcimat** [comment]
Big thanks for this fix :)

**Comment by rscarson** [comment]
@mvriel At the risk of sounding stupid, and just for future information, I was wondering why several directories, notably the Descriptor directory are missing in the dev. branch

**Comment by mvriel** [comment]
@rscarson that question is not stupid at all, the develop branch of phpDocumentor is the branch where we develop phpDocumentor v3 and most of that part of the application has been moved to the Reflection package

**Comment by rscarson** [comment]
@mvriel Thanks!

**Comment by p4d** [comment]
Hello, i still have the error using the 2.9.0 version.

**Comment by navii1991** [comment]
hello guys, i m also facing the error "Argument $varname is missing from the Docblock of methodname" using the latest version 2.9.0 .
