### ISSUE TITLE
Incorrect relative URLs created by @link/@see when used as inline tags

### ISSUE THREAD

**Issue by PhrozenByte** [phpDocumentor/phpDocumentor2#1672]
When using a inline `@link` or `@see` tag to reference a class or method, phpDocumentor 2.8.5 doesn't take the base URL into account and creates invalid relative URLs. The following phpDoc results in [this method doc](http://picocms.org/phpDoc/master/classes/Pico.html#method_getPlugin). Please note the invalid URLs for `PicoPluginInterface` in the method description. Inline tags referencing methods are broken, too ([Example](http://picocms.org/phpDoc/master/classes/Pico.html#method_setConfig)). This only happens when used as inline tags, also note the correct URLs in the `See also` section on the right.

```php
    /**
     * Returns the instance of a named plugin
     *
     * Plugins SHOULD implement {@link PicoPluginInterface}, but you MUST NOT
     * rely on it. For more information see {@link PicoPluginInterface}.
     *
     * @see    Pico::loadPlugins()
     * @see    Pico::getPlugins()
     * @param  string           $pluginName name of the plugin
     * @return object                       instance of the plugin
     * @throws RuntimeException             thrown when the plugin wasn't found
     */
```

**Comment by mvriel** [comment]
I see what you mean, the `Clean` template seems to remove the relative path where the documentation is installed; so instead of referencing `http://picocms.org/phpDoc/master/classes/Pico.html#method___construct` it references `http://picocms.org/classes/Pico.html#method___construct`. This smells like an issue with the root path determination in the Twig Extension but to be sure we'd need to look deeper.

**Comment by mvriel** [comment]
This has been resolved in a recent pull request against phpDocumentor's master branch. We do have to tag and do a new release before this is available on PEAR or with the Phar

**Comment by PhrozenByte** [comment]
Thank you! :+1:

**Comment by smileBeda** [comment]
This is different now, but I can still see some issue (which might be expected?). When it is added in a main description block part, in _most_ cases it works, but if added to another tag, such as `@since` or even `@atts` or any else, it does not parse at all and just returns raw, or as `{@see}` (raw without the actual "see" link)

Not sure if this is supposed to work or not, because https://github.com/phpDocumentor/phpDocumentor/issues/546 says it has been fixed but I cannot see this working _in other than the description_ (such as inline with other tags)

---

In some cases, it also fails in the main description section, and if it fails, then it produces `lore ipsum %1$s lorem ipsum` where `%1$s` is the part that represents the inline `@see` tag.

Docblock:
```
/**
 * Lorem ipsum {@see SomeClass::SomeMethod()}.
 */
```
This last issue however seems to be related to https://github.com/pronamic/wp-documentor rather than PHPDocumentor, since it happens to me only in documented _filters and actions_.
