### ISSUE TITLE
DOCKER phpdoc/phpdoc generate Parameters with error Count

### ISSUE THREAD

**Issue by smithpl2000** [phpDocumentor/phpDocumentor2#2023]
When you use docker pulled from official phpdoc and run it, you got an error on generated page:
"Warning: count(): Parameter must be an array or an object that implements Countable in /opt/phpdoc/vendor/twig/twig/lib/Twig/Extension/Core.php on line 1275 Warning: count(): Parameter must be an array or an object that implements Countable in /opt/phpdoc/vendor/twig/twig/lib/Twig/Extension/Core.php on line 1275"

## Expected Behavior
generate correct view

## Steps to Reproduce the Problem

  1. docker pull phpdoc/phpdoc
  2. docker run --rm -v $(pwd):/data phpdoc/phpdoc
  3. See on generated page Summary for some object 

## Your environment

* Docker-ce Leatest

**Comment by FelipoAntonoff** [comment]
I'm also having the same problem, even using the latest Phar version 2.
The error appears in parts of the generated documentation.

**Comment by FelipoAntonoff** [comment]
Check this fix:
https://github.com/phpDocumentor/phpDocumentor2/issues/1914#issuecomment-415014566

Resolved for my case, I use PHP 7.2, that in case using Phar, in any case it worked normally.

**Comment by jaapio** [comment]
Dupplicate of #1914

**Comment by vanomak** [comment]
still have this warning from the offical docker image, why this issue is closed?

**Comment by jaapio** [comment]
Because it is a duplicate. Like I said before...
